spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hackatonifcode2019
    username: hackatonifcode2019
    password: hackatonifcode2019
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/liquibase/liquibase-changelog.yaml